language: python
# python versions
python:
  - "3.8"

# install requirements
install:
  - cd api
  - cd api && pip install -r requirements.txt
  - pip install coveralls
# To run tests
script:
  - cd api && coverage run --source='.' manage.py test
# send coverage report to coveralls
after_success:
  coveralls
